<?php
$sql[] = "INSERT INTO `endpoint_models` (`brand`, `model`, `type`, `softkeys`, `firmware`, `accounts`) VALUES ('digium', 'D70', 'phone', '65', '', '6')";
$sql[] = "INSERT INTO `endpoint_models` (`brand`, `model`, `type`, `softkeys`, `firmware`, `accounts`) VALUES ('digium', 'D50', 'phone', '13', '', '4')";
$sql[] = "INSERT INTO `endpoint_models` (`brand`, `model`, `type`, `softkeys`, `firmware`, `accounts`) VALUES ('digium', 'D40', 'phone', '1', '', '2')";
$sql[] = "INSERT INTO `endpoint_models` (`brand`, `model`, `type`, `softkeys`, `firmware`, `accounts`) VALUES ('digium', 'D45', 'phone', '1', '', '2')";

$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'accounts', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'accounts', '0', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0status', '1')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0register', '1')"; 
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0account_id', '%line1Ext%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0username', '%line1Ext%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0authname', '%line1Ext%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0password', '%line1Pass%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0passcode', '%line1Pass%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0line_label', '%line1Name%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0caller_id', '%line1Name%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0dial_plan', '[0-8]xxxxx|911|9411|9611|9011xxx.T3|91xxxxxxxxxx|9[2-9]xxxxxx|*xx.T3|[0-8]xx.T3')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0visual_voicemail', '0')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0voicemail', '*97')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0outbound_proxy', '')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0outbound_port', '')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0conflict', 'replace')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0host_primary', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0server', '%line1Dest%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0port', '%line1sipPort%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0transport', 'udp')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0reregister', '300')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0retry', '25')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '0', '0num_retries', '5')";

$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'accounts', '1', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1status', '%line2Enable%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1register', '%line2Enable%')"; 
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1account_id', '%line2Ext%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1username', '%line2Ext%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1authname', '%line2Ext%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1password', '%line2Pass%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1passcode', '%line2Pass%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1line_label', '%line2Name%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1caller_id', '%line2Name%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1dial_plan', '[0-8]xxxxx|911|9411|9611|9011xxx.T3|91xxxxxxxxxx|9[2-9]xxxxxx|*xx.T3|[0-8]xx.T3')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1visual_voicemail', '0')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1voicemail', '%voicemail%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1outbound_proxy', '')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1outbound_port', '')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1conflict', 'replace')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1host_primary', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1server', '%line2Dest%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1port', '%line2sipPort%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1transport', 'udp')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1reregister', '300')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1retry', '25')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '1', '1num_retries', '5')";

$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'accounts', '2', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2status', '%line3Enable%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2register', '%line3Enable%')"; 
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2account_id', '%line3Ext%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2username', '%line3Ext%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2authname', '%line3Ext%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2password', '%line3Pass%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2passcode', '%line3Pass%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2line_label', '%line3Name%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2caller_id', '%line3Name%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2dial_plan', '[0-8]xxxxx|911|9411|9611|9011xxx.T3|91xxxxxxxxxx|9[2-9]xxxxxx|*xx.T3|[0-8]xx.T3')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2visual_voicemail', '0')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2voicemail', '%voicemail%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2outbound_proxy', '')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2outbound_port', '')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2conflict', 'replace')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2host_primary', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2server', '%line3Dest%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2port', '%line3sipPort%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2transport', 'udp')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2reregister', '300')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2retry', '25')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '2', '2num_retries', '5')";

$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'accounts', '3', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3status', '%line4Enable%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3register', '%line4Enable%')"; 
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3account_id', '%line4Ext%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3username', '%line4Ext%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3authname', '%line4Ext%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3password', '%line4Pass%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3passcode', '%line4Pass%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3line_label', '%line4Name%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3caller_id', '%line4Name%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3dial_plan', '[0-8]xxxxx|911|9411|9611|9011xxx.T3|91xxxxxxxxxx|9[2-9]xxxxxx|*xx.T3|[0-8]xx.T3')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3visual_voicemail', '0')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3voicemail', '%voicemail%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3outbound_proxy', '')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3outbound_port', '')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3conflict', 'replace')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3host_primary', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3server', '%line4Dest%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3port', '%line4sipPort%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3transport', 'udp')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3reregister', '300')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3retry', '25')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '3', '3num_retries', '5')";

$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'accounts', '4', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4status', '%line5Enable%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4register', '%line5Enable%')"; 
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4account_id', '%line5Ext%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4username', '%line5Ext%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4authname', '%line5Ext%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4password', '%line5Pass%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4passcode', '%line5Pass%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4line_label', '%line5Name%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4caller_id', '%line5Name%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4dial_plan', '[0-8]xxxxx|911|9411|9611|9011xxx.T3|91xxxxxxxxxx|9[2-9]xxxxxx|*xx.T3|[0-8]xx.T3')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4visual_voicemail', '0')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4voicemail', '%voicemail%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4outbound_proxy', '')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4outbound_port', '')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4conflict', 'replace')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4host_primary', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4server', '%line5Dest%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4port', '%line5sipPort%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4transport', 'udp')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4reregister', '300')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4retry', '25')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '4', '4num_retries', '5')";

$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'accounts', '5', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5status', '%line6Enable%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5register', '%line6Enable%')"; 
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5account_id', '%line6Ext%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5username', '%line6Ext%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5authname', '%line6Ext%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5password', '%line6Pass%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5passcode', '%line6Pass%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5line_label', '%line6Name%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5caller_id', '%line6Name%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5dial_plan', '[0-8]xxxxx|911|9411|9611|9011xxx.T3|91xxxxxxxxxx|9[2-9]xxxxxx|*xx.T3|[0-8]xx.T3')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5visual_voicemail', '0')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5voicemail', '%voicemail%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5outbound_proxy', '')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5outbound_port', '')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5conflict', 'replace')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5host_primary', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5server', '%line6Dest%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5port', '%line6sipPort%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5transport', 'udp')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5reregister', '300')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5retry', '25')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', '5', '5num_retries', '5')";

/*
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'accounts', 'host_primary', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'host_primary', 'server', '%line1Dest%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'host_primary', 'port', '%line1sipPort%')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'host_primary', 'transport', 'udp')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'host_primary', 'reregister', '300')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'host_primary', 'retry', '25')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'host_primary', 'num_retries', '5')";
*/
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"login_password\"', 'value=\"%adminPass%\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"time_zone\"', 'value=\"%timezone%\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"time_source\"', 'value=\"ntp\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"ntp_server\"', 'value=\"%timeserver1%\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"ntp_resync\"', 'value=\"86400\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"accept_local_calls\"', 'value=\"any\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"transport_udp_enabled\"', 'value=\"1\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"transport_udp_port\"', 'value=\"%sipPort%\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"transport_tcp_enabled\"', 'value=\"1\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"transport_tcp_port\"', 'value=\"%sipPort%\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"logo_file\"', 'value=\"user\" path=\"/user_image.png\" url=\"%background%\" md5=\"%bgimagehash%\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"display_mc_notification\"', 'value=\"1\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"brightness\"', 'value=\"10\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"contrast\"', 'value=\"10\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"dim_backlight\"', 'value=\"1\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"backlight_timeout\"', 'value=\"30\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"backlight_dim_level\"', 'value=\"2\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"ringer_volume\"', 'value=\"5\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"speaker_volume\"', 'value=\"5\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"handset_volume\"', 'value=\"5\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"headset_volume\"', 'value=\"5\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"reset_call_volume\"', 'value=\"0\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"default_ringtone\"', 'value=\"Digium\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"active_ringtone\"', 'value=\"Digium\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"headset_answer\"', 'value=\"0\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"desi_strip_enable\"', 'value=\"1\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"enable_blf_on_unused_line_keys\"', 'value=\"1\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"name_format\"', 'value=\"first_last\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"contacts_max_subscriptions\"', 'value=\"60\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"blf_contact_group\"', 'value=\"Default\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"network_enable_dhcp\"', 'value=\"1\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"network_static_ip_address\"', 'value=\"\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"network_subnet_mask\"', 'value=\"\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"network_default_gateway\"', 'value=\"\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"network_domain_name\"', 'value=\"\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"network_primary_dns_server\"', 'value=\"\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"network_secondary_dns_server\"', 'value=\"\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"network_vlan_discovery_mode\"', 'value=\"NONE\" network=\"10.10.0.0/16\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"sip_qos\"', 'value=\"0\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"rtp_qos\"', 'value=\"0\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"pc_qos\"', 'value=\"0\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"network_vlan_id\"', 'value=\"44\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"log_level\"', 'value=\"debug\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"enable_logging\"', 'value=\"0\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"log_server\"', 'value=\"10.1.2.3\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"log_port\"', 'value=\"514\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"web_ui_enabled\"', 'value=\"1\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"sip_dscp\"', 'value=\"24\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"rtp_dscp\"', 'value=\"46\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"udp_ka_interval\"', 'value=\"60\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"enable_check_sync\"', 'value=\"1\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"locale\"', 'value=\"en_US\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'setting id=\"ehs\"', 'value=\"auto\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'contacts url', '=\"%provisionAddress%/%line1Ext%.xml\" id=\"internal\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'smart_blf', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'smart_blf', 'blf_items', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'blf_items', 'url', '\"%provisionAddress%/%line1Ext%-blf.xml\"')";

$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'MiscSettings', 'PARENT')";

$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'permission', 'id', '\"record_own_calls\" value=\"0\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'codecs', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'codecs', 'codec', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'codec', 'id', '\"PCMU\" priority=\"255\" packetization=\"20\" jitter_min=\"0\" jitter_max=\"0\" jitter_target=\"0\" enabled=\"1\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'codec', 'id', '\"PCMA\" priority=\"13\" packetization=\"20\" jitter_min=\"0\" jitter_max=\"0\" jitter_target=\"0\" enabled=\"1\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'codec', 'id', '\"G722\" priority=\"11\" packetization=\"20\" jitter_min=\"0\" jitter_max=\"0\" jitter_target=\"0\" enabled=\"1\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'codec', 'id', '\"G726-32\" priority=\"7\" packetization=\"20\" jitter_min=\"0\" jitter_max=\"0\" jitter_target=\"0\" enabled=\"1\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'codec', 'id', '\"G729\" priority=\"4\" packetization=\"20\" jitter_min=\"0\" jitter_max=\"0\" jitter_target=\"0\" enabled=\"1\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'codec', 'id', '\"L16\" priority=\"2\" packetization=\"20\" jitter_min=\"0\" jitter_max=\"0\" jitter_target=\"0\" enabled=\"1\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'codec', 'id', '\"L16-256\" priority=\"1\" packetization=\"20\" jitter_min=\"0\" jitter_max=\"0\" jitter_target=\"0\" enabled=\"1\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'ringtones', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'ringtones', 'tones', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'tones', 'tone', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'tone', 'id', '\"Alarm\" display=\"Alarm\" type=\"phone\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'tone', 'id', '\"Chimes\" display=\"Chimes\" type=\"phone\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'tone', 'id', '\"Digium\" display=\"Digium\" type=\"phone\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'tone', 'id', '\"GuitarStrum\" display=\"Guitar Strum\" type=\"phone\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'tone', 'id', '\"Jingle\" display=\"Jingle\" type=\"phone\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'tone', 'id', '\"Office\" display=\"Office\" type=\"phone\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'tone', 'id', '\"Office2\" display=\"Office 2\" type=\"phone\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'tone', 'id', '\"RotaryPhone\" display=\"Rotary Phone\" type=\"phone\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'tone', 'id', '\"SteelDrum\" display=\"Steel Drum\" type=\"phone\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'tone', 'id', '\"Techno\" display=\"Techno\" type=\"phone\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'tone', 'id', '\"Theme\" display=\"Theme\" type=\"phone\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'tone', 'id', '\"Tweedle\" display=\"Tweedle\" type=\"phone\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'tone', 'id', '\"Twinkle\" display=\"Twinkle\" type=\"phone\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'tone', 'id', '\"Vibe\" display=\"Vibe\" type=\"phone\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'ringtones', 'alerts', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'alerts', 'alert', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'alert', 'alert_info', '\"normal\" ringtone_id=\"Digium\" ring_type=\"normal\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'alert', 'alert_info', '\"ring-answer\" ringtone_id=\"Digium\" ring_type=\"ring-answer\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'alert', 'alert_info', '\"intercom\"  ringtone_id=\"\"  ring_type=\"answer\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'alert', 'alert_info', '\"visual\"  ringtone_id=\"\"  ring_type=\"visual\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'TOP', 'firmwares', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'firmwares', 'firmware', 'PARENT')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'firmware', 'model', '\"D50\" version=\"%version%\" url=\"http://%destination%:%provisionport%/digium/%firmware%D50.eff\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'firmware', 'model', '\"D70\" version=\"%version%\" url=\"http://%destination%:%provisionport%/digium/%firmware%D70.eff\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'firmware', 'model', '\"D40\" version=\"%version%\" url=\"http://%destination%:%provisionport%/digium/%firmware%D40.eff\"')";
$sql[] = "INSERT INTO `endpoint_basefiles` (`brand`, `template`,  `model`, `type`, `attrib`, `param`, `value`) VALUES ('digium', 'default', '', 'phone', 'firmware', 'model', '\"D45\" version=\"%version%\" url=\"http://%destination%:%provisionport%/digium/%firmware%D45.eff\"')";
